"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenType = void 0;
var TokenType;
(function (TokenType) {
    TokenType[TokenType["KEYWORD"] = 0] = "KEYWORD";
    TokenType[TokenType["IDENTIFIER"] = 1] = "IDENTIFIER";
    TokenType[TokenType["LPAREN"] = 2] = "LPAREN";
    TokenType[TokenType["RPAREN"] = 3] = "RPAREN";
    TokenType[TokenType["COMMA"] = 4] = "COMMA";
    TokenType[TokenType["STRING"] = 5] = "STRING";
    TokenType[TokenType["NUMBER"] = 6] = "NUMBER";
    TokenType[TokenType["NULL"] = 7] = "NULL";
    TokenType[TokenType["GREATER_THAN"] = 8] = "GREATER_THAN";
    TokenType[TokenType["LESS_THAN"] = 9] = "LESS_THAN";
    TokenType[TokenType["GREATER_OR_EQUAL_THAN"] = 10] = "GREATER_OR_EQUAL_THAN";
    TokenType[TokenType["LESS_OR_EQUAL_THAN"] = 11] = "LESS_OR_EQUAL_THAN";
    TokenType[TokenType["EQUAL"] = 12] = "EQUAL";
    TokenType[TokenType["EOF"] = 13] = "EOF";
})(TokenType || (exports.TokenType = TokenType = {}));
